# Generated by Django 4.1.1 on 2022-09-20 12:08

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_super_admin_account(apps, schema_editor):

    User = apps.get_model("app", "User")

    user = User.objects.create(
        system_id="RONIADMIN001",
        first_name="ADMIN ACCOUNT",
        email="admin@admin.com",
        mobile_number="09123456789",
        user_type="admin",
        is_superadmin=True
    )

    user.password = make_password("admin")
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_super_admin_account)
    ]
