# Generated by Django 4.1.1 on 2022-11-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='amount_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
