# Generated by Django 4.1.1 on 2022-11-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cashier_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
