# Generated by Django 4.1.1 on 2022-11-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='number_of_pieces',
        ),
    ]
