# Generated by Django 4.1.1 on 2022-11-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sales_amount_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='unit_of_measure',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
