# Generated by Django 4.1.1 on 2022-11-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_listing_number_of_pieces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='unit_of_measure',
        ),
    ]
