# Generated by Django 4.1.1 on 2022-11-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_listing_unit_of_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='quantity',
        ),
    ]
