# Generated by Django 4.1.1 on 2022-12-05 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_listing_unit_of_measure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='truck_driver',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='truck_plate_number',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='GroupStockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=250, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=250, null=True)),
                ('received_by', models.CharField(blank=True, max_length=250, null=True)),
                ('truck_plate_number', models.CharField(blank=True, max_length=250, null=True)),
                ('truck_driver', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stockin',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.groupstockin'),
        ),
    ]
