# Generated by Django 4.1.1 on 2022-12-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sales_options_remove_stockin_checked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
