# Generated by Django 4.1.1 on 2022-10-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockout',
            name='sales_price',
        ),
    ]
