# Generated by Django 4.1.1 on 2022-10-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_stockin_store_stockout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockout',
            name='delivered_to',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
