# Generated by Django 4.1.1 on 2022-11-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_stockout_sales_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockout',
            name='number_of_pieces',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
