# Generated by Django 4.1.1 on 2023-01-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_stockin_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='groupstockin',
            name='sales_invoice_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
