# Generated by Django 4.1.1 on 2023-01-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstockin',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='groupstockin',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
            preserve_default=False,
        ),
    ]
