# Generated by Django 4.1.1 on 2023-01-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_truckdriver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstockin',
            name='truck_driver',
        ),
        migrations.AddField(
            model_name='groupstockin',
            name='new_truck_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.truckdriver'),
        ),
    ]
