# Generated by Django 4.1.1 on 2023-01-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_stockout_checked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='stockin',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
