# Generated by Django 4.1.1 on 2023-01-30 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_product_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstockin',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='groupstockin',
            name='received_by',
        ),
        migrations.AddField(
            model_name='groupstockin',
            name='checked_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_checked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupstockin',
            name='received_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_received_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
