# Generated by Django 4.1.1 on 2023-02-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_groupstockin_checked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
